services:
  app:
    build:
      context: ..
      dockerfile: ProdDocker/Dockerfile
    expose:
      - "3000"
    restart: unless-stopped
    networks:
      - web-network

networks:
  web-network:
    name: web-network
    driver: bridge
