services:
  app:
    build:
      context: ..
      dockerfile: ProdDocker/Dockerfile
    expose:
      - "3000"
    restart: unless-stopped

networks:
  default:
    name: web-network
    external: true
