stages:
  - deploy

deploy_production:
  stage: deploy
  only:
    - main
  tags:
    - self-hosted
  script:
    - docker builder prune -f
    - docker container prune -f
    - docker system df
    - docker compose -f ProdDocker/docker-compose.yml up -d --build
